create_port -direction in wb_adr_i_31_
create_port -direction in wb_adr_i_30_
create_port -direction in wb_adr_i_29_
create_port -direction in wb_adr_i_28_
create_port -direction in wb_adr_i_27_
create_port -direction in wb_adr_i_26_
create_port -direction in wb_adr_i_25_
create_port -direction in wb_adr_i_24_
create_port -direction in wb_adr_i_23_
create_port -direction in wb_adr_i_22_
create_port -direction in wb_adr_i_21_
create_port -direction in wb_adr_i_20_
create_port -direction in wb_adr_i_19_
create_port -direction in wb_adr_i_18_
create_port -direction in wb_adr_i_17_
create_port -direction in wb_adr_i_16_
create_port -direction in wb_adr_i_15_
create_port -direction in wb_adr_i_14_
create_port -direction in wb_adr_i_13_
create_port -direction in wb_adr_i_12_
create_port -direction in wb_adr_i_11_
create_port -direction in wb_adr_i_10_
create_port -direction in wb_adr_i_9_
create_port -direction in wb_adr_i_8_
create_port -direction in wb_adr_i_7_
create_port -direction in wb_adr_i_6_
create_port -direction in wb_adr_i_1_
create_port -direction in wb_adr_i_0_
create_port -direction in wb_cyc_i
create_port -direction in wb_dat_i_31_
create_port -direction in wb_dat_i_30_
create_port -direction in wb_dat_i_29_
create_port -direction in wb_dat_i_28_
create_port -direction in wb_dat_i_27_
create_port -direction in wb_dat_i_26_
create_port -direction in wb_dat_i_25_
create_port -direction in wb_dat_i_24_
create_port -direction in wb_dat_i_23_
create_port -direction in wb_dat_i_22_
create_port -direction in wb_dat_i_21_
create_port -direction in wb_dat_i_20_
create_port -direction in wb_dat_i_19_
create_port -direction in wb_dat_i_18_
create_port -direction in wb_dat_i_17_
create_port -direction in wb_dat_i_16_
create_port -direction in wb_dat_i_15_
create_port -direction in wb_dat_i_14_
create_port -direction in wb_dat_i_13_
create_port -direction in wb_dat_i_12_
create_port -direction in wb_dat_i_11_
create_port -direction in wb_dat_i_10_
create_port -direction in wb_dat_i_9_
create_port -direction in wb_dat_i_8_
create_port -direction in wb_dat_i_7_
create_port -direction in wb_dat_i_6_
create_port -direction in wb_dat_i_5_
create_port -direction in wb_dat_i_4_
create_port -direction in wb_dat_i_3_
create_port -direction in wb_dat_i_2_
create_port -direction in wb_dat_i_1_
create_port -direction in wb_sel_i_3_
create_port -direction in wb_sel_i_2_
create_port -direction in wb_sel_i_1_
create_port -direction in wb_sel_i_0_
create_port -direction in sfllKey_75_
create_port -direction in sfllKey_74_
create_port -direction in sfllKey_73_
create_port -direction in sfllKey_72_
create_port -direction in sfllKey_71_
create_port -direction in sfllKey_70_
create_port -direction in sfllKey_69_
create_port -direction in sfllKey_68_
create_port -direction in sfllKey_67_
create_port -direction in sfllKey_66_
create_port -direction in sfllKey_65_
create_port -direction in sfllKey_64_
create_port -direction in sfllKey_63_
create_port -direction in sfllKey_62_
create_port -direction in sfllKey_61_
create_port -direction in sfllKey_60_
create_port -direction in sfllKey_59_
create_port -direction in sfllKey_58_
create_port -direction in sfllKey_57_
create_port -direction in sfllKey_56_
create_port -direction in sfllKey_55_
create_port -direction in sfllKey_54_
create_port -direction in sfllKey_53_
create_port -direction in sfllKey_52_
create_port -direction in sfllKey_51_
create_port -direction in sfllKey_50_
create_port -direction in sfllKey_49_
create_port -direction in sfllKey_48_
create_port -direction in sfllKey_47_
create_port -direction in sfllKey_46_
create_port -direction in sfllKey_45_
create_port -direction in sfllKey_44_
create_port -direction in sfllKey_43_
create_port -direction in sfllKey_42_
create_port -direction in sfllKey_41_
create_port -direction in sfllKey_40_
create_port -direction in sfllKey_39_
create_port -direction in sfllKey_38_
create_port -direction in sfllKey_37_
create_port -direction in sfllKey_36_
create_port -direction in sfllKey_35_
create_port -direction in sfllKey_34_
create_port -direction in sfllKey_33_
create_port -direction in sfllKey_32_
create_port -direction in sfllKey_31_
create_port -direction in sfllKey_30_
create_port -direction in sfllKey_29_
create_port -direction in sfllKey_28_
create_port -direction in sfllKey_27_
create_port -direction in sfllKey_26_
create_port -direction in sfllKey_25_
create_port -direction in sfllKey_24_
create_port -direction in sfllKey_23_
create_port -direction in sfllKey_22_
create_port -direction in sfllKey_21_
create_port -direction in sfllKey_20_
create_port -direction in sfllKey_19_
create_port -direction in sfllKey_18_
create_port -direction in sfllKey_17_
create_port -direction in sfllKey_16_
create_port -direction in sfllKey_15_
create_port -direction in sfllKey_14_
create_port -direction in sfllKey_13_
create_port -direction in sfllKey_12_
create_port -direction in sfllKey_11_
create_port -direction in sfllKey_10_
create_port -direction in sfllKey_9_
create_port -direction in sfllKey_8_
create_port -direction in sfllKey_7_
create_port -direction in sfllKey_6_
create_port -direction in sfllKey_5_
create_port -direction in sfllKey_4_
create_port -direction in sfllKey_3_
create_port -direction in sfllKey_2_
create_port -direction in sfllKey_1_
create_port -direction in sfllKey_0_
create_port -direction in fllkey_79_
create_port -direction in fllkey_78_
create_port -direction in fllkey_77_
create_port -direction in fllkey_76_
create_port -direction in fllkey_75_
create_port -direction in fllkey_74_
create_port -direction in fllkey_73_
create_port -direction in fllkey_72_
create_port -direction in fllkey_71_
create_port -direction in fllkey_70_
create_port -direction in fllkey_69_
create_port -direction in fllkey_68_
create_port -direction in fllkey_67_
create_port -direction in fllkey_66_
create_port -direction in fllkey_65_
create_port -direction in fllkey_64_
create_port -direction in fllkey_63_
create_port -direction in fllkey_62_
create_port -direction in fllkey_61_
create_port -direction in fllkey_60_
create_port -direction in fllkey_59_
create_port -direction in fllkey_58_
create_port -direction in fllkey_57_
create_port -direction in fllkey_56_
create_port -direction in fllkey_55_
create_port -direction in fllkey_54_
create_port -direction in fllkey_53_
create_port -direction in fllkey_52_
create_port -direction in fllkey_51_
create_port -direction in fllkey_50_
create_port -direction in fllkey_49_
create_port -direction in fllkey_48_
create_port -direction in fllkey_47_
create_port -direction in fllkey_46_
create_port -direction in fllkey_45_
create_port -direction in fllkey_44_
create_port -direction in fllkey_43_
create_port -direction in fllkey_42_
create_port -direction in fllkey_41_
create_port -direction in fllkey_40_
create_port -direction in fllkey_39_
create_port -direction in fllkey_38_
create_port -direction in fllkey_37_
create_port -direction in fllkey_36_
create_port -direction in fllkey_35_
create_port -direction in fllkey_34_
create_port -direction in fllkey_33_
create_port -direction in fllkey_32_
create_port -direction in fllkey_31_
create_port -direction in fllkey_30_
create_port -direction in fllkey_29_
create_port -direction in fllkey_28_
create_port -direction in fllkey_27_
create_port -direction in fllkey_26_
create_port -direction in fllkey_25_
create_port -direction in fllkey_24_
create_port -direction in fllkey_23_
create_port -direction in fllkey_22_
create_port -direction in fllkey_21_
create_port -direction in fllkey_20_
create_port -direction in fllkey_19_
create_port -direction in fllkey_18_
create_port -direction in fllkey_17_
create_port -direction in fllkey_16_
create_port -direction in fllkey_15_
create_port -direction in fllkey_14_
create_port -direction in fllkey_13_
create_port -direction in fllkey_12_
create_port -direction in fllkey_11_
create_port -direction in fllkey_10_
create_port -direction in fllkey_9_
create_port -direction in fllkey_8_
create_port -direction in fllkey_7_
create_port -direction in fllkey_6_
create_port -direction in fllkey_5_
create_port -direction in fllkey_4_
create_port -direction in fllkey_3_
create_port -direction in fllkey_2_
create_port -direction in fllkey_1_
create_port -direction in fllkey_0_
create_port -direction out wb_err_o
connect_net logic_net0     wb_err_o
create_port -direction out int_o
connect_net logic_net0     int_o
create_port -direction out wb_ack_o
connect_net logic_net1     wb_ack_o
